# Vendor Master Data Quality

Initial scope: SAP-style vendor master data.

Phase 1 focus:
- General vendor data
- Data profiling
- Deterministic Data Quality rules
- Duplicate and similarity analysis later

In [4]:
import pandas as pd
vendor_columns = [
    "LIFNR",
    "LAND1",
    "NAME1",
    "NAME2",
    "ORT01",
    "PSTLZ",
    "STRAS",
    "TELF1",
    "STCD1",
    "SPERR",
    "LOEVM"
]

len(vendor_columns)

11

In [ ]:
vendor_data = {
    "LIFNR": [
        "100001", "100002", "100003", "100004", "100005",
        "100006", "100007", "100008", "100009", "100010",
        "100011", "100012"
    ],

    "LAND1": [
        "AE", "AE", "AE", "OM", "AE",
        "AE", "AE", None, "AE", "OM",
        "AE", "AE"
    ],

    "NAME1": [
        "Gulf Trading LLC",
        "Gulf Trading L.L.C.",
        "Al Noor Services",
        "Muscat Industrial Co",
        None,
        "Desert Engineering LLC",
        "DESERT ENGINEERING L.L.C",
        "Emirates Technical Services",
        "Al Falah Trading",
        "Oman Equipment Services",
        "Future Tech Solutions",
        "Future Tech Solution LLC"
    ],

    "NAME2": [
        None,
        None,
        "Maintenance Division",
        None,
        None,
        None,
        None,
        None,
        "Abu Dhabi Branch",
        None,
        None,
        None
    ],

    "ORT01": [
        "Abu Dhabi",
        "Abu Dhabi",
        "Dubai",
        "Muscat",
        "Dubai",
        "Abu Dhabi",
        "ABU DHABI",
        "Sharjah",
        "AbuDhabi",
        "Muscat",
        "Dubai",
        "Dubai"
    ],

    "PSTLZ": [
        "12345",
        "12345",
        None,
        "112",
        "00000",
        "45678",
        "45678",
        "54321",
        "12A45",
        "113",
        "67890",
        "67890"
    ],

    "STRAS": [
        "Mussafah Industrial Area",
        "Mussafah Ind. Area",
        "Sheikh Zayed Road",
        "Ruwi Industrial Estate",
        None,
        "Street 10, Mussafah",
        "Street 10 Mussafah",
        "Industrial Area 4",
        "Hamdan Street",
        "Ghala Industrial Area",
        "Business Bay Tower 2",
        "Business Bay, Tower 2"
    ],

    "TELF1": [
        "+971501234567",
        "0501234567",
        "+971 55 222 3344",
        "+96899112233",
        None,
        "02-5556677",
        "+97125556677",
        "12345",
        "+971501111222",
        "+968 24 567890",
        "+971504445555",
        "0504445555"
    ],

    "STCD1": [
        "100234567890003",
        "100234567890003",
        "100345678900003",
        "OM1234567",
        None,
        "100456789010003",
        "100456789010003",
        "ABC123",
        "100567890120003",
        "OM9876543",
        "100678901230003",
        "100678901230003"
    ],

    "SPERR": [
        "", "", "", "", "",
        "", "X", "", "", "",
        "", ""
    ],

    "LOEVM": [
        "", "", "", "", "",
        "", "", "", "X", "",
        "", ""
    ]
}


vendor_raw = pd.DataFrame(vendor_data)
#print(vendor_raw.info())
vendor_work = vendor_raw.copy()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LIFNR   12 non-null     str
 1   LAND1   11 non-null     str
 2   NAME1   11 non-null     str
 3   NAME2   2 non-null      str
 4   ORT01   12 non-null     str
 5   PSTLZ   11 non-null     str
 6   STRAS   11 non-null     str
 7   TELF1   11 non-null     str
 8   STCD1   11 non-null     str
 9   SPERR   12 non-null     str
 10  LOEVM   12 non-null     str
dtypes: str(11)
memory usage: 1.2 KB
None

In [89]:
vendor_work.head(2)

dq_results = pd.DataFrame( columns=["LIFNR","RULE_ID","DQ_DIMENSION","FIELD","ISSUE"])
dq_results

Empty DataFrame
Columns: [LIFNR, RULE_ID, DQ_DIMENSION, FIELD, ISSUE]
Index: []

In [90]:
def add_dq_results(dq_results, condition, field, rule_id, dq_dimension, issue):
    rule_results = vendor_work[condition][["LIFNR"]].copy()
    rule_results["RULE_ID"]=rule_id
    rule_results["DQ_DIMENSION"] = dq_dimension
    rule_results["FIELD"] = field
    rule_results["ISSUE"]= issue

    dq_results = pd.concat([dq_results, rule_results], ignore_index = True)

    return dq_results

In [92]:
#dq_results = add_dq_results(dq_results,vendor_work["NAME1"].isna(),'NAME1','DQ0001','Completeness','NAME1 is missing')
dq_results = add_dq_results(dq_results,vendor_work["NAME2"].isna(),'NAME2','DQ0002','Completeness','NAME2 is missing')
dq_results

     LIFNR RULE_ID  DQ_DIMENSION  FIELD             ISSUE
0   100005  DQ0001  Completeness  NAME1  NAME1 is missing
1   100001  DQ0002  Completeness  NAME2  NAME2 is missing
2   100002  DQ0002  Completeness  NAME2  NAME2 is missing
3   100004  DQ0002  Completeness  NAME2  NAME2 is missing
4   100005  DQ0002  Completeness  NAME2  NAME2 is missing
5   100006  DQ0002  Completeness  NAME2  NAME2 is missing
6   100007  DQ0002  Completeness  NAME2  NAME2 is missing
7   100008  DQ0002  Completeness  NAME2  NAME2 is missing
8   100010  DQ0002  Completeness  NAME2  NAME2 is missing
9   100011  DQ0002  Completeness  NAME2  NAME2 is missing
10  100012  DQ0002  Completeness  NAME2  NAME2 is missing